INSERT INTO Alue (id, aikaleima, otsikko, teksti) VALUES (1, 0, 'Ponit', 'Ponit (koska ne on mahtavia!)');
INSERT INTO Alue (id, aikaleima, otsikko, teksti) VALUES (2, 0, 'Hevoiset', 'Hevoslajit');
INSERT INTO Alue (id, aikaleima, otsikko, teksti) VALUES (3, 0, 'Offtopic', 'Kaikenlaista sekavaa juttua');
INSERT INTO Aihe (id, aikaleima, alue, nimimerkki, otsikko, teksti) VALUES (1, 0, 1, 'nuorzi', 'Ponit ovat parhaat', '(puuttuu)');
INSERT INTO Aihe (id, aikaleima, alue, nimimerkki, otsikko, teksti) VALUES (2, 1, 2, 'zille', 'Islanninhevoset', '(puuttuu)');
INSERT INTO Aihe (id, aikaleima, alue, nimimerkki, otsikko, teksti) VALUES (3, 2, 1, 'zille', 'Pokemon-ponit', '(puuttuu)');
INSERT INTO Aihe (id, aikaleima, alue, nimimerkki, otsikko, teksti) VALUES (4, 3, 1, 'nuorzi', 'Ponit on ihania!!!', 'Eiks ookin???');
INSERT INTO Aihe (id, aikaleima, alue, nimimerkki, otsikko, teksti) VALUES (5, 4, 1, 'nuorzi', 'Ponit on söpöjä!!!', 'Onks kaikki samaa mieltä???');
INSERT INTO Viesti (id, aikaleima, aihe, nimimerkki, teksti) VALUES (1, 0, 3, 'zille', 'Charmander on paras Pokemon-poni');
INSERT INTO Viesti (id, aikaleima, aihe, nimimerkki, teksti) VALUES (2, 1, 2, 'zille', 'En tykkää islanninhevosista...');
INSERT INTO Viesti (id, aikaleima, aihe, nimimerkki, teksti) VALUES (3, 2, 2, 'nuorzi', 'Siis onko muka joku joka ei tykkää islanninhevosista???');
